### ISSUE TITLE
Compilation errors on M1 macOS

### ISSUE THREAD

**Issue by Cupnfish** [substrate-developer-hub/substrate-node-template#249]
**Description**

It does not compile properly under m1's mac.

**Steps to Reproduce**

The direct use of `cargo run -release - -dev -tmp`

**Expected vs. Actual Behavior**

Expected it to work, but it didn't, an error was reported.

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system: macOS Big Sur 11.6(20G165)
- Template version/tag: v3.0.0+monthly-2021-10
- Rust version (run `rustup show`):
```shell
Default host: aarch64-apple-darwin
rustup home:  /Users/cupnfish/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2021-08-10-aarch64-apple-darwin
nightly-2021-09-23-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)
1.52.1-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
wasm32-unknown-unknown
x86_64-linux-android

active toolchain
----------------

nightly-aarch64-apple-darwin (default)
rustc 1.57.0-nightly (c02371c44 2021-10-01)
```

**Logs, Errors or Screenshots**
```shell
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1191:22: Unexpected type for `Single` constructor: <futures::future::PollFn<[closure@/Users/cupnfish/.cargo/git/checkouts/substrate-7e08433d4c370a21/bf9683e/client/offchain/src/api/http.rs:192:60: 192:86]> as futures::Future>::Output

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (c02371c44 2021-10-01) running on aarch64-apple-darwin

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `api::http::<impl at /Users/cupnfish/.cargo/git/checkouts/substrate-7e08433d4c370a21/bf9683e/client/offchain/src/api/http.rs:130:1: 500:2>::request_write_body::{closure#1}`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `sc-offchain`
warning: build failed, waiting for other jobs to finish...
error: build failed

substrate-node-template on  master via 🦀 v1.57.0-nightly took 6m41s 
❯ cargo run --release -- --dev --tmp
   Compiling librocksdb-sys v6.20.3
   Compiling sc-offchain v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)
   Compiling sc-network-gossip v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)
   Compiling sc-rpc-api v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)
   Compiling node-template-runtime v3.0.0-monthly-2021-10 (/Users/cupnfish/Documents/GitHub/substrate-node-template/runtime)
   Compiling rocksdb v0.17.0
   Compiling kvdb-rocksdb v0.14.0
   Compiling sc-client-db v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-10#bf9683ee)
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1191:22: Unexpected type for `Single` constructor: <futures::future::PollFn<[closure@/Users/cupnfish/.cargo/git/checkouts/substrate-7e08433d4c370a21/bf9683e/client/offchain/src/api/http.rs:192:60: 192:86]> as futures::Future>::Output

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (c02371c44 2021-10-01) running on aarch64-apple-darwin

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `api::http::<impl at /Users/cupnfish/.cargo/git/checkouts/substrate-7e08433d4c370a21/bf9683e/client/offchain/src/api/http.rs:130:1: 500:2>::request_write_body::{closure#1}`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `sc-offchain`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Additional Information**

Is this a Rust internal error?

**Comment by Cupnfish** [comment]
This is indeed an internal Rust bug, update to the latest version of nightly and you'll be fine.
