### ISSUE TITLE
Build error when trying to create a function that takes a `T::AccountId` along with `Origin`.

### ISSUE THREAD

**Issue by stonecharioteer** [substrate-developer-hub/substrate-node-template#371]
Hi,
I'm trying to learn more about how to build my own pallet, and I ran into a problem. [This is my repo](https://github.com/stonecharioteer/substrate-node-connect-four/tree/feat/connect-four), and the code builds fine. However, when I try to use [the public polkadot web app](https://polkadot.js.org/apps/) to interact with my pallet's `new_game` method, I immediately get the following error:

```
====================

Version: 4.0.0-dev-1d837406994

0: sp_panic_handler::set::{{closure}}
1: std::panicking::rust_panic_with_hook
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
2: std::panicking::begin_panic_handler::{{closure}}
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
3: std::sys_common::backtrace::__rust_end_short_backtrace
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
4: rust_begin_unwind
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
5: core::panicking::panic_fmt
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
6: node_template_runtime::api::dispatch
7: std::thread::local::LocalKey<T>::with
8: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
9: sc_executor::wasm_runtime::RuntimeCache::with_instance
10: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
11: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
12: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
13: <sc_rpc::state::state_full::FullState<BE,Block,Client> as sc_rpc::state::StateBackend<Block,Client>>::call
14: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
16: tokio::runtime::task::harness::Harness<T,S>::poll
17: tokio::runtime::blocking::pool::Inner::run
18: std::sys_common::backtrace::__rust_begin_short_backtrace
19: core::ops::function::FnOnce::call_once{{vtable.shim}}
20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
std::sys::unix::thread::Thread::new::thread_start
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
21: start_thread
at ./nptl/./nptl/pthread_create.c:442:8
22: clone3
at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81


Thread 'tokio-runtime-worker' panicked at 'Bad input data provided to query_info: Could not decode `MultiAddress`, variant doesn't exist', runtime/src/lib.rs:337

This is a bug. Please report it at:

support.anonymous.an
```

I am not sure if it's something I'm doing wrong. Could someone help?

**Comment by stonecharioteer** [comment]
Oops. I figured out what I was doing wrong. I was using ensure! to raise an error and that kept panicking.
